### ISSUE TITLE
sunday data is  not removed . 

### ISSUE THREAD

**Issue by jain203** [virresh/StockD#14]
Sunday data is not filtered . so we get duplicate data on every sunday. plz remove this bug.  
image attached.
![image](https://user-images.githubusercontent.com/63539232/99217372-eb21c480-27fd-11eb-87b0-532dca7579cb.png)

**Comment by virresh** [comment]
Hi @jain203

Thanks for reporting, I don't use Amibroker so I cannot check for this bug. Can you give some additional details?

Do you get any .txt file for Sunday in the chosen downloaded location?
Or does this happen only after importing the files in the software?

**Comment by jain203** [comment]
text file for sunday oct- 18
[ALL_2020OCT18.txt](https://github.com/virresh/StockD/files/5637022/ALL_2020OCT18.txt)

**Comment by virresh** [comment]
Interesting
Thanks for the sample text file @jain203 

I have identified the issue

NSE's servers actually save data for previous friday on Sunday's data, which confuses the downloader when it's looking for data

Concretely, you can actually download data by feeding in Sunday on NSE website
As a proof, try visiting (18th Oct 2020, Sunday)
https://archives.nseindia.com/products/content/sec_bhavdata_full_18102020.csv
You will get a csv file but with data of 16th Oct

But if you go to (17th Oct 2020, Saturday)
https://archives.nseindia.com/products/content/sec_bhavdata_full_17102020.csv
there will be no file downloaded, which is as expected


This only happens on the delivery data server, not on indices or futures (or other equity servers) and is very annoying. For now you have a couple of options:
- You can go to Advanced tab and Check the skip weekends option. Downside is you'll have to manually uncheck and download data in case Market opens on a saturday
- You can switch to a better server if you don't use delivery data. Go to Advanced tab -> Load Link Profile from and select another server such as NSE Archives or NSE Daily.

Since this issue is not in downloader, but in the NSE Servers, It will take a while for me to see what I can do from my side to solve this issue. 

Feel free to reply to this thread if the above two suggestions don't help

**Comment by jain203** [comment]
thanks for replay, can you tell any software of python script that can download raw bhav copy of eq and fno. that i can use for my analysis.


thanks
regards Abhishek jain
________________________________

**Comment by jain203** [comment]
________________________________

**Comment by jain203** [comment]
thanks  virresh, Sunday data is removed by Check the skip weekends option but we still get data for non weekends holiday .

**Comment by virresh** [comment]
Thanks for reporting.
I think I have a permanent fix that I can apply on the software side to ensure that any files whose date doesn't match the expected date will be rejected. 

I'll release the fixes as soon as I get some time to work on this. Will update this thread once I release the newer version.

**Comment by virresh** [comment]
@jain203 
I have fixed this issue with v4.6
Link to download: https://github.com/virresh/StockD/releases/latest


Please test and feel free to re-open this issue / comment here in case it doesn't fix the issue for you.
