### ISSUE TITLE
equity bhacopy not downloading where as nseeodfixed is working

### ISSUE THREAD

**Issue by mithu4200** [virresh/StockD#8]
today saw that equity bhavcopy not downloded how ever indices and future bhavcopy is downloading .pls check

**Comment by virresh** [comment]
I see.
Thanks for reporting

Is this issue for other days also?

**Comment by virresh** [comment]
@mithu4200 I think this problem is because NSE has not uploaded bhavcopy delivery data file 
You can switch to another link profile and get data for that day.
Instructions for switching link profiles are given in https://github.com/virresh/StockD/wiki/User-Guide#what-are-link-profiles below the link profile table.

Closing this issue since it's not a problem of downloader. It's problem of NSE not uploading delivery data. You can use a different link profile to avoid this issue.

Feel free to open this issue in case anything is unclear.
